[auth]
redirect_uri = "https://fvconsulting.streamlit.app/oauth2callback"
cookie_secret = "cookie_secret = "7e8b2f6d1f3b4c5a9d8e7f6a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c"

client_id = "890816086487-1knjm73dl5i9grb1pnra58gnq4s8glvb.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
