[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "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"
client_id = "890816086487-1knjm73dl5i9grb1pnra58gnq4s8glvb.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
890816086487-1knjm73dl5i9grb1pnra58gnq4s8glvb.apps.googleusercontent.com